development:
  adapter: postgresql
  encoding: unicode
  database: google_agenda_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: google_agenda_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: google_agenda_production
  pool: 5
  username: root
  password:
